# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracker.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'tracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtracker.proto\x12\x07tracker\"\x94\x01\n\x04Ping\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\x12\x0b\n\x03\x61lt\x18\x04 \x01(\x01\x12\x0c\n\x04hdop\x18\x05 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x06 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x07 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x08 \x01(\x02\x12\x11\n\ttimestamp\x18\t \x01(\x03\")\n\tSyncBatch\x12\x1c\n\x05pings\x18\x01 \x03(\x0b\x32\r.tracker.PingB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_PING']._serialized_start=27
  _globals['_PING']._serialized_end=175
  _globals['_SYNCBATCH']._serialized_start=177
  _globals['_SYNCBATCH']._serialized_end=218
# @@protoc_insertion_point(module_scope)
