/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRACKER_TRACKER_PB_H_INCLUDED
#define PB_TRACKER_TRACKER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _tracker_Ping {
    /* Device identifier (we limit this to 16 chars in Nanopb options) */
    pb_callback_t device_id;
    /* GPS Coordinates */
    double lat;
    double lon;
    double alt; /* Altitude in meters */
    /* Signal Quality */
    float hdop; /* Horizontal Dilution of Precision */
    /* Physics / IMU Data (Used to calculate RPM and Wobble) */
    float accel_x;
    float accel_y;
    float accel_z;
    /* Time of capture (Unix epoch time) */
    int64_t timestamp;
} tracker_Ping;

typedef struct _tracker_SyncBatch {
    pb_callback_t pings;
} tracker_SyncBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define tracker_Ping_init_default                {{{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0}
#define tracker_SyncBatch_init_default           {{{NULL}, NULL}}
#define tracker_Ping_init_zero                   {{{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0}
#define tracker_SyncBatch_init_zero              {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define tracker_Ping_device_id_tag               1
#define tracker_Ping_lat_tag                     2
#define tracker_Ping_lon_tag                     3
#define tracker_Ping_alt_tag                     4
#define tracker_Ping_hdop_tag                    5
#define tracker_Ping_accel_x_tag                 6
#define tracker_Ping_accel_y_tag                 7
#define tracker_Ping_accel_z_tag                 8
#define tracker_Ping_timestamp_tag               9
#define tracker_SyncBatch_pings_tag              1

/* Struct field encoding specification for nanopb */
#define tracker_Ping_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         1) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               2) \
X(a, STATIC,   SINGULAR, DOUBLE,   lon,               3) \
X(a, STATIC,   SINGULAR, DOUBLE,   alt,               4) \
X(a, STATIC,   SINGULAR, FLOAT,    hdop,              5) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           6) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,           8) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         9)
#define tracker_Ping_CALLBACK pb_default_field_callback
#define tracker_Ping_DEFAULT NULL

#define tracker_SyncBatch_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  pings,             1)
#define tracker_SyncBatch_CALLBACK pb_default_field_callback
#define tracker_SyncBatch_DEFAULT NULL
#define tracker_SyncBatch_pings_MSGTYPE tracker_Ping

extern const pb_msgdesc_t tracker_Ping_msg;
extern const pb_msgdesc_t tracker_SyncBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define tracker_Ping_fields &tracker_Ping_msg
#define tracker_SyncBatch_fields &tracker_SyncBatch_msg

/* Maximum encoded size of messages (where known) */
/* tracker_Ping_size depends on runtime parameters */
/* tracker_SyncBatch_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
